<?php

namespace Database\Seeders;

use App\Models\Kegiatan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KegiatanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'id_program' => 1,
                'nama' => 'Pemberian  Honor Guru TK dan PAUD',
                'status' => 'sedangBerjalan',
                'volume' => '25',
                'satuan' => 'ok',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => 'TK/PAUD',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 1,
                'nama' => 'Pemberian PMT TK dan PAUD',
                'status' => 'sedangBerjalan',
                'volume' => '80',
                'satuan' => 'siswa',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => 'TK/PAUD',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 1,
                'nama' => 'Honor Guru TPA',
                'status' => 'sedangBerjalan',
                'volume' => '5',
                'satuan' => 'ok',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => 'TK/PAUD',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 2,
                'nama' => 'Penyuluhan Pentingnya Jam belajar masyarakat',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'ls',
                'tahun_1' => 0,
                'tahun_2' => 1,
                'tahun_3' => 0,
                'tahun_4' => 1,
                'tahun_5' => 0,
                'tahun_6' => 1,
                'lokasi' => 'Kal. Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 3,
                'nama' => 'Pembangunan Atap dan Paving TK Pertiwi 46',
                'status' => 'sedangBerjalan',
                'volume' => '2',
                'satuan' => 'paket',
                'tahun_1' => 0,
                'tahun_2' => 1,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'TK Pertiwi 46',
                'id_dusun' => 13,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 3,
                'nama' => 'Pembangunan Keramik Lantai TK Pertiwi 46',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'paket',
                'tahun_1' => 0,
                'tahun_2' => 1,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'TK Pertiwi 46',
                'id_dusun' => 13,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 3,
                'nama' => 'Pembuatan Kanopi APE Luar dan Pagar PAUD Jebugan',
                'status' => 'sedangBerjalan',
                'volume' => '2',
                'satuan' => 'paket',
                'tahun_1' => 0,
                'tahun_2' => 1,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'PAUD Jebugan',
                'id_dusun' => 11,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 4,
                'nama' => 'Pengelolaan Perpustakaan Milik Desa',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'ls',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => 'Kal. Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 5,
                'nama' => 'Pemberian subsidi bagi siswa miskin dan siswa berprestasi',
                'status' => 'sedangBerjalan',
                'volume' => '45',
                'satuan' => 'paket',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => 'Kal. Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 6,
                'nama' => 'PMT balita dan lansia',
                'status' => 'sedangBerjalan',
                'volume' => '12',
                'satuan' => 'kali',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => '15 Padukuhan',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 6,
                'nama' => 'Honor PMK dan Tim Monitoring Posyandu',
                'status' => 'sedangBerjalan',
                'volume' => '12',
                'satuan' => 'kali',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => '15 Padukuhan',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 6,
                'nama' => 'Honor Kader Posyandu',
                'status' => 'sedangBerjalan',
                'volume' => '12',
                'satuan' => 'kali',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => '4 Orang',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 7,
                'nama' => 'Penyuluhan/ rembug Stunting',
                'status' => 'sedangBerjalan',
                'volume' => '2',
                'satuan' => 'kali',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => 'Kal. Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 7,
                'nama' => 'Penyuluhan Bumil Risti',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'kali',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => 'Kal. Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 7,
                'nama' => 'Bimtek KADER Kesehatan',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'kali',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => 'Kal. Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 8,
                'nama' => 'Penyelenggaraan Desa Siaga Kesehatan',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'paket',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => 'Kal. Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 9,
                'nama' => 'Penyuluhan Pola Asuh Anak',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'paket',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => 'Kal. Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 10,
                'nama' => 'Pengadaan APE Dalam dan APE Luar',
                'status' => 'sedangBerjalan',
                'volume' => '15',
                'satuan' => 'paket',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => '15 Padukuhan',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 10,
                'nama' => 'Pengadaan Alat Kesehatan',
                'status' => 'sedangBerjalan',
                'volume' => '15',
                'satuan' => 'paket',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => '15 Padukuhan',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 10,
                'nama' => 'Pengadaan Peralatan Penunjang Posyandu (Sound, Laptop, Proyektor, Printer, dll)',
                'status' => 'sedangBerjalan',
                'volume' => '15',
                'satuan' => 'paket',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => '15 Padukuhan',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 11,
                'nama' => 'Fasilitasi WKSBM',
                'status' => 'sedangBerjalan',
                'volume' => '15',
                'satuan' => 'paket',
                'tahun_1' => 0,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => '15 Padukuhan',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 12,
                'nama' => 'Fasilitasi Kampung KB Karangweru',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'paket',
                'tahun_1' => 0,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => 'Karangweru',
                'id_dusun' => 12,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 13,
                'nama' => 'Pengelolaan Kalurahan Inklusi',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'paket',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => 'Kal. Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 14,
                'nama' => 'Penanganan Stunting (PMT Stunting)',
                'status' => 'sedangBerjalan',
                'volume' => '24',
                'satuan' => 'kali',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => 'Kal. Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 15,
                'nama' => 'Pendampingan Ibu Hamil Risti (PMT Bumil Risti)',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'paket',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => 'Kal. Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 16,
                'nama' => 'Pelaksanaan PSN (15 Padukuhan)',
                'status' => 'sedangBerjalan',
                'volume' => '15',
                'satuan' => 'kali',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => '15 Padukuhan',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 17,
                'nama' => 'Pembangunan / Rehabilitasi / Peningkatan / Pengerasan Jalan Desa',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 1,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Kal. Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 18,
                'nama' => 'Corblok RT 01,02,04',
                'status' => 'sedangBerjalan',
                'volume' => '400',
                'satuan' => 'meter',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 1,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Plesan',
                'id_dusun' => 2,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 18,
                'nama' => 'Urug halaman eks SD Blantik',
                'status' => 'sedangBerjalan',
                'volume' => '600',
                'satuan' => 'meter',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 1,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Plesan',
                'id_dusun' => 2,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 18,
                'nama' => 'Corblok jalan Timur Blantik',
                'status' => 'direncanakan',
                'volume' => '250',
                'satuan' => 'meter',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Plesan',
                'id_dusun' => 2,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 19,
                'nama' => 'Rehabilitas Jalan Usaha Tani',
                'status' => 'sedangBerjalan',
                'volume' => '300',
                'satuan' => 'meter',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 1,
                'lokasi' => 'Kalurahan Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 20,
                'nama' => 'Perbaikan Jembatan Dusun Gaten',
                'status' => 'sedangBerjalan',
                'volume' => '4',
                'satuan' => 'meter',
                'tahun_1' => 0,
                'tahun_2' => 1,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Gaten',
                'id_dusun' => 10,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 20,
                'nama' => 'Rehab Jembatan Karen (SLB)',
                'status' => 'sedangBerjalan',
                'volume' => '3',
                'satuan' => 'meter',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 1,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Karen',
                'id_dusun' => 4,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 20,
                'nama' => 'Gorong-gorong Dusun Bracan',
                'status' => 'sedangBerjalan',
                'volume' => '200',
                'satuan' => 'meter',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 1,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Bracan',
                'id_dusun' => 7,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 21,
                'nama' => 'Rehab Gorong-gorong Jalan Kab Jl. Celep Donotirto',
                'status' => 'sedangBerjalan',
                'volume' => '2500',
                'satuan' => 'meter',
                'tahun_1' => 0,
                'tahun_2' => 1,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Kal. Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 21,
                'nama' => 'Gorong-gorong Dusun Bracan',
                'status' => 'sedangBerjalan',
                'volume' => '200',
                'satuan' => 'meter',
                'tahun_1' => 0,
                'tahun_2' => 1,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Bracan',
                'id_dusun' => 7,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 21,
                'nama' => 'Pembangunan Bangket dan Drainase Kalurahan Tirtomulyo',
                'status' => 'sedangBerjalan',
                'volume' => '50',
                'satuan' => 'meter',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 1,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Kalurahan Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 22,
                'nama' => 'Pembangunan Gedung Pertemuan / Balai Dusun Soropadan',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 1,
                'tahun_6' => 0,
                'lokasi' => 'Soropadan',
                'id_dusun' => 15,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 22,
                'nama' => 'Bangket jalan RT 03',
                'status' => 'sedangBerjalan',
                'volume' => '150',
                'satuan' => 'meter',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 1,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Kergan',
                'id_dusun' => 6,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 22,
                'nama' => 'Balai Dusun 15 Padukuhan',
                'status' => 'sedangBerjalan',
                'volume' => '15',
                'satuan' => 'unit',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => '15 Padukuhan',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 23,
                'nama' => 'Rehab Pagar Makam dusun Gaten dan Karen',
                'status' => 'sedangBerjalan',
                'volume' => '50',
                'satuan' => 'meter',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 1,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Gaten dan Karen',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 23,
                'nama' => 'Rehab Makam dusun Genting',
                'status' => 'sedangBerjalan',
                'volume' => '75',
                'satuan' => 'meter',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 1,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Genting',
                'id_dusun' => 13,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 23,
                'nama' => 'Pengadaan Tratag untuk Makam dusun Tokolan',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 1,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Tokolan',
                'id_dusun' => 8,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 24,
                'nama' => 'Rehab Gapura Punduhan',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 1,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Punduhan',
                'id_dusun' => 17,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 24,
                'nama' => 'Pembangunan Gapura Selamat Datang di dusun Soropadan',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 1,
                'tahun_6' => 0,
                'lokasi' => 'Soropadan',
                'id_dusun' => 15,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 24,
                'nama' => 'Pembangunan Gapura Plesan',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 1,
                'lokasi' => 'Plesan',
                'id_dusun' => 2,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 25,
                'nama' => 'Pengembangan Sentra Budaya Adat',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 1,
                'lokasi' => 'Karen',
                'id_dusun' => 4,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Pengembangan pusat studi budaya yang di khususkan untuk padukuhan Karen',
            ],
            [
                'id_program' => 25,
                'nama' => 'Pembangunan Joglo Sanggar Budaya',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 1,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Kalurahan Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 26,
                'nama' => 'Pembangunan Ruang Layak Anak / Area Bermain',
                'status' => 'sedangBerjalan',
                'volume' => '15',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 1,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => '15 Padukuhan',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 26,
                'nama' => 'Pembangunan Area Bermain di Kantor Kalurahan Tirtomulyo',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 1,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Kalurahan Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 27,
                'nama' => 'RTLH di 15 Padukuhan',
                'status' => 'sedangBerjalan',
                'volume' => '75',
                'satuan' => 'unit',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => 'Kalurahan Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 28,
                'nama' => 'Pemeliharaan Sanitasi di Dusun Gaten',
                'status' => 'sedangBerjalan',
                'volume' => '75',
                'satuan' => 'meter',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 1,
                'tahun_6' => 0,
                'lokasi' => 'Gaten',
                'id_dusun' => 10,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 29,
                'nama' => 'Pembangunan MCK 15 Padukuhan',
                'status' => 'sedangBerjalan',
                'volume' => '45',
                'satuan' => 'paket',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => '15 Padukuhan',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 30,
                'nama' => 'Pengelolaan sampah dan pengadaan sarana prasarana pengelolaan sampah pada 15 padukuhan',
                'status' => 'sedangBerjalan',
                'volume' => '15',
                'satuan' => 'paket',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => '15 Padukuhan',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 30,
                'nama' => 'Pengadaan gerobak sampah dan pelatihan pengelolaan sampah',
                'status' => 'sedangBerjalan',
                'volume' => '30',
                'satuan' => 'orang',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => 'Kalurahan Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 30,
                'nama' => 'Pembuatan bak sampah lingkungan rumah untuk dusun karen',
                'status' => 'sedangBerjalan',
                'volume' => '45',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 1,
                'tahun_6' => 0,
                'lokasi' => 'Karen',
                'id_dusun' => 4,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 31,
                'nama' => 'Pembangunan Taman Bermain Anak',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 1,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Kantor Kalurahan Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 31,
                'nama' => 'Pembangunan Taman Hijau Desa',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 1,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Kantor Kalurahan Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 32,
                'nama' => 'Pembangunan PAMSIMAS',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 1,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Kalurahan Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 33,
                'nama' => 'Pembangunan IPAL Komunal Padukuhan Gondangan',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 1,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Gondangan',
                'id_dusun' => 5,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 34,
                'nama' => 'Bantuan Listrik untuk Masyarakat Miskin',
                'status' => 'sedangBerjalan',
                'volume' => '25',
                'satuan' => 'unit',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => 'Kalurahan Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 35,
                'nama' => 'Pembangunan Taman di tepi jalan Protokol untuk dusun Genting',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'paket',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 1,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Genting',
                'id_dusun' => 13,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 36,
                'nama' => 'Pembangunan Rumah Pilah Sampah',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 1,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Kalurahan Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 36,
                'nama' => 'Pengelolaan Rumah Pilah Sampah Kalurahan',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 1,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Kalurahan Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 36,
                'nama' => 'Pembuatan bak sampah lingkungan rumah',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 1,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Kalurahan Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 37,
                'nama' => 'Pelatihan Pengelolaan Sampah',
                'status' => 'sedangBerjalan',
                'volume' => '15',
                'satuan' => 'kali',
                'tahun_1' => 1,
                'tahun_2' => 1,
                'tahun_3' => 1,
                'tahun_4' => 1,
                'tahun_5' => 1,
                'tahun_6' => 1,
                'lokasi' => '15 Padukuhan',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 38,
                'nama' => 'Pengembangan tanaman obat keluarga untuk dusun Bracan dan Gaten',
                'status' => 'sedangBerjalan',
                'volume' => '2',
                'satuan' => 'paket',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 1,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Bracan dan Gaten',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 38,
                'nama' => 'Penanaman sayuran di pekarangan dengan sistem Polibag untuk dusun Gondangan',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'paket',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 1,
                'lokasi' => 'Gondangan',
                'id_dusun' => 5,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 38,
                'nama' => 'Penanaman sayuran di pekarangan dengan sistem Hidroponik untuk dusun Gondangan',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'paket',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 1,
                'tahun_6' => 0,
                'lokasi' => 'Gondangan',
                'id_dusun' => 5,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 39,
                'nama' => 'Pengadaan cermin rambu jalan untuk pertigaan dusun gondangan RT 04',
                'status' => 'sedangBerjalan',
                'volume' => '2',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 1,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Gondangan',
                'id_dusun' => 5,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 39,
                'nama' => 'Pengadaan rambu jalan dari dusun karen sampai dusun tokolan',
                'status' => 'sedangBerjalan',
                'volume' => '15',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 1,
                'tahun_6' => 0,
                'lokasi' => 'Tokolan',
                'id_dusun' => 8,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 39,
                'nama' => 'Rambu - rambu pintu masuk dusun Karen',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 1,
                'tahun_6' => 0,
                'lokasi' => 'Karen',
                'id_dusun' => 4,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 40,
                'nama' => 'Pengadaan Papan Nama di 3 Gardu Padukuhan Karen',
                'status' => 'sedangBerjalan',
                'volume' => '3',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 1,
                'tahun_6' => 0,
                'lokasi' => 'Karen',
                'id_dusun' => 4,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 40,
                'nama' => 'Pengadaan Papan Pengumuman untuk Dusun Bracan',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 1,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Bracan',
                'id_dusun' => 7,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 41,
                'nama' => 'Pengembangan KIM untuk dusun Gondangan dan Karangweru',
                'status' => 'sedangBerjalan',
                'volume' => '2',
                'satuan' => 'paket',
                'tahun_1' => 1,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Gondangan dan Karangweru',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 42,
                'nama' => 'Pengadaan sarana penerangan jalan utuk masjid sampai RT 1 dusun Bracan',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 1,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Bracan',
                'id_dusun' => 7,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 42,
                'nama' => 'Pengadaan sarana penerangan jalan utama RT 04 Bracan',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 1,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Bracan',
                'id_dusun' => 7,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 42,
                'nama' => 'Pengadaan Sarana Penerangan jalan lingkungan RT 03 Gondangan',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 1,
                'lokasi' => 'Gondangan',
                'id_dusun' => 5,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 43,
                'nama' => 'Pembangunan Talut',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 1,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Kergan',
                'id_dusun' => 6,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 43,
                'nama' => 'Rehab Kolam untuk padukuhan Kergan',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 1,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Kergan',
                'id_dusun' => 6,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 43,
                'nama' => 'Pembuatan Taman Hijau (ikon Wisata Kampung Gurami)',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 1,
                'tahun_2' => 0,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Kergan',
                'id_dusun' => 6,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 44,
                'nama' => 'Pentas Seni Promo Wisata',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 1,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Kalurahan Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
            [
                'id_program' => 44,
                'nama' => 'Pembentukan Pokdarwis',
                'status' => 'sedangBerjalan',
                'volume' => '1',
                'satuan' => 'unit',
                'tahun_1' => 0,
                'tahun_2' => 1,
                'tahun_3' => 0,
                'tahun_4' => 0,
                'tahun_5' => 0,
                'tahun_6' => 0,
                'lokasi' => 'Kalurahan Tirtomulyo',
                'id_dusun' => 1,
                'longitude' => '110.29903178662545',
                'latitude' => '-7.970050904904937',
                'deskripsi' => 'Lorem Awiwum',
            ],
        ];

        /*
        kiri atas:   -7.957413, 110.278170
        kanan bawah: -7.981636, 110.305603
        */

        foreach($data as $kegiatan) {
            // ganti ke int
            $latFloat = (float)$kegiatan['latitude'];
            $lonFloat = (float)$kegiatan['longitude'];
            // random()
            $minLat = -7.957413;
            $maxLat = -7.981636;
            $minLon = 110.278170;
            $maxLon = 110.305603;

            $randomLat = $minLat + mt_rand() / mt_getrandmax() * ($maxLat - $minLat);
            $randomLon = $minLon + mt_rand() / mt_getrandmax() * ($maxLon - $minLon);
            // balikkestrig()
            Kegiatan::create([
                'id_program' => $kegiatan['id_program'],
                'nama' => $kegiatan['nama'],
                'volume' => $kegiatan['volume'],
                'status' => $kegiatan['status'],
                'satuan' => $kegiatan['satuan'],
                'tahun_1'=> $kegiatan['tahun_1'],
                'tahun_2'=> $kegiatan['tahun_2'],
                'tahun_3'=> $kegiatan['tahun_3'],
                'tahun_4'=> $kegiatan['tahun_4'],
                'tahun_5'=> $kegiatan['tahun_5'],
                'tahun_6'=> $kegiatan['tahun_6'],
                'lokasi'=> $kegiatan['lokasi'],
                'id_dusun'=> $kegiatan['id_dusun'],
                'longitude'=> (string)$randomLon,
                'latitude'=> (string)$randomLat,
                'deskripsi'=> $kegiatan['deskripsi'],
            ]);
        };
    }
}
